version: "3.7"
services:
  redis:
    image: redis:latest
    volumes:
      - orm_data_redis:/data
    ports:
      - "4000:6379"
  mysql:
    image: mysql:8.0
    ports:
      - "4001:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=ice_db
      - MYSQL_USER=$DB_USERNAME
      - MYSQL_PASSWORD=$DB_PASSWORD
    volumes:
      - orm_data_mysql:/var/lib/mysql


volumes:
  orm_data_mysql:
  orm_data_redis:
